version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb 
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/mongo    

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq     
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/data/mq

  postgres:
    image: postgres:17
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongo_data:
  rabbit_data:
  postgres_data:
