version: "3.9"

services:
  mongo:
    image: mongo:7.0
    container_name: mongodb 
    restart: unless-stopped

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/mongo    

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq     
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_data:/data/mq

volumes:
  mongo_data:
  rabbit_data:
